import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  return (
    <div className=" bg-primaryWhite">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Homepage</h1>
      <Footer />
    </div>
  )
}

export default Home
