#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Format with Prettier & Check Eslint Standards before commiting
yarn lint-staged ||
(
    echo 'lint staged failed to run';
    false;
)

# Check tsconfig standards
yarn check-types ||
(
    echo 'Failed Type check. Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ I am committing this now. ✅✅✅✅'